<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE widget [
        <!ELEMENT widget (name|description|author|feature|preference|icon|gap:plugin|access)*>
        <!ATTLIST widget
                id CDATA #REQUIRED
                version CDATA #REQUIRED
                xmlns CDATA #REQUIRED
                xmlns:gap CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ATTLIST author
                email CDATA #REQUIRED
                href CDATA #REQUIRED>
        <!ELEMENT feature (param)*>
        <!ATTLIST feature
                name CDATA #REQUIRED>
        <!ELEMENT preference (#PCDATA)>
        <!ATTLIST preference
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT param (#PCDATA)>
        <!ATTLIST param
                name CDATA #REQUIRED
                value CDATA #REQUIRED>
        <!ELEMENT icon (#PCDATA)>
        <!ATTLIST icon
                gap:density CDATA #IMPLIED
                gap:platform CDATA #IMPLIED
                height CDATA #IMPLIED
                src CDATA #REQUIRED
                width CDATA #IMPLIED>
        <!ELEMENT gap:plugin (#PCDATA)>
        <!ATTLIST gap:plugin
                name CDATA #REQUIRED>
        <!ELEMENT access (#PCDATA)>
        <!ATTLIST access
                origin CDATA #REQUIRED>
        ]>
<widget id="com.openspace.quest" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:gap="http://phonegap.com/ns/1.0">
    <name>QuestApp</name>
    <description>
        Quest your friends to vent, share, dig, or challenege
    </description>
    <author email="jrose@openspaceapps.com" href="http://www.openspaceapps.com">
        OpenSpaceApps
    </author>
    <feature name="http://api.phonegap.com/1.0/device" />
    <preference name="fullscreen" value="true" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="prerendered-icon" value="true" />
    <preference name="DisallowOverscroll" value="false" />
    <preference name="KeyboardDisplayRequiresUserAction" value="false" />
    <feature name="Device">
        <param name="ios-package" value="CDVDevice" />
    </feature>
    <feature name="Contacts">
        <param name="android-package" value="org.apache.cordova.contacts.ContactManager" />
    </feature>
    <feature name="Contacts">
        <param name="ios-package" value="CDVContacts" />
    </feature>
    <feature name="GAPlugin" >
        < param name="android-package" value="com.adobe.plugins.GAPlugin"/>
    </feature>
    <feature name="GAPlugin" >
        < param name="ios-package" value="com.adobe.plugins.GAPlugin"/>
    </feature>
    <preference name="permissions" value="none" />
    <preference name="orientation" value="default" />
    <preference name="target-device" value="universal" />
    <preference name="prerendered-icon" value="true" />
    <preference name="stay-in-webview" value="false" />
    <preference name="ios-statusbarstyle" value="black-opaque" />
    <preference name="detect-data-types" value="true" />
    <preference name="exit-on-suspend" value="false" />
    <preference name="show-splash-screen-spinner" value="true" />
    <preference name="auto-hide-splash-screen" value="true" />
    <preference name="disable-cursor" value="false" />
    <preference name="android-minSdkVersion" value="7" />
    <preference name="android-installLocation" value="auto" />
    <preference name="KeyboardShrinksView" value="true" />
    <preference name="android-windowSoftInputMode" value="stateVisible|adjustResize" />
    <preference name="windowSoftInputMode" value="adjustResize" />
    <icon src="icon.png" />
    <icon gap:density="ldpi" gap:platform="android" src="icons/android/ldpi.png" />
    <icon gap:density="mdpi" gap:platform="android" src="icons/android/mdpi.png" />
    <icon gap:density="hdpi" gap:platform="android" src="icons/android/hdpi.png" />
    <icon gap:density="xhdpi" gap:platform="android" src="icons/android/xhdpi.png" />
    <icon gap:platform="ios" height="57" src="icons/ios/icon.png" width="57" />
    <icon gap:platform="ios" height="72" src="icons/ios/icon-72.png" width="72" />
    <icon gap:platform="ios" height="114" src="icons/ios/icon_at_2x.png" width="114" />
    <icon gap:platform="ios" height="144" src="icons/ios/icon-72_at_2x.png" width="144" />
    <feature name="http://api.phonegap.com/1.0/contacts"/>
    <!-- Core plugins -->
    <gap:plugin name="org.apache.cordova.battery-status" />
    <gap:plugin name="org.apache.cordova.camera" />
    <gap:plugin name="org.apache.cordova.media-capture" />
    <gap:plugin name="org.apache.cordova.console" />
    <gap:plugin name="org.apache.cordova.contacts" />
    <gap:plugin name="org.apache.cordova.device" />
    <gap:plugin name="org.apache.cordova.device-motion" />
    <gap:plugin name="org.apache.cordova.device-orientation" />
    <gap:plugin name="org.apache.cordova.dialogs" />
    <gap:plugin name="org.apache.cordova.file" />
    <gap:plugin name="org.apache.cordova.file-transfer" />
    <gap:plugin name="org.apache.cordova.geolocation" />
    <gap:plugin name="org.apache.cordova.globalization" />
    <gap:plugin name="org.apache.cordova.inappbrowser" />
    <gap:plugin name="org.apache.cordova.media" />
    <gap:plugin name="org.apache.cordova.network-information" />
    <gap:plugin name="org.apache.cordova.splashscreen" />
    <gap:plugin name="org.apache.cordova.vibration" />
    <gap:plugin name="de.phonostar.softkeyboard" />
    <!-- GCM project number: 635140378165 -->
    <!-- API key: AIzaSyD-wjrqeMA3CHhJXTTGhl8CJH6hjACEJQE -->
    <gap:plugin name="com.adobe.plugins.pushplugin" />

    <access origin="*" />
</widget>